#!/bin/bash

set -eu

echo "(chroot) 6.20" "Shadow"
echo "Approximate build time:" "0.2 SBU"
echo "Required disk space:" "46 MB"
echo

package=shadow-*.tar.xz
tmpDir=/tmp/shadow

# extract packages in a tmp dir
tar -xf /sources/$package -C /tmp/
mv -v $tmpDir* $tmpDir
pushd $tmpDir

# disable the installation of the groups program and its man pages
sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;

# use the more secure SHA-512 method of pass encryption
sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs

# make the first group number generated by useradd
sed -i 's/1000/999/' etc/useradd

# configure
./configure --sysconfdir=/etc --with-group-name-max-length=32

# compile
make

# install
make install

# move a misplaced program
mv -v /usr/bin/passwd /bin

# removes tmp dir
popd
rm -rf $tmpDir

# enable shadowed passwords and group passwords
pwconv
grpconv
